/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ottoalexander
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Alumno NAlumno=null; 
    Alumno NuevoAlumno = new Alumno();
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sex = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        card = new javax.swing.JTextField();
        Info_Alumno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ActualCarrier = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NewCarrier = new javax.swing.JTextField();
        Info_Alumno1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Iage = new javax.swing.JLabel();
        Iname = new javax.swing.JLabel();
        Isex = new javax.swing.JLabel();
        Icard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Info1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Iname1 = new javax.swing.JLabel();
        Iage1 = new javax.swing.JLabel();
        Isex1 = new javax.swing.JLabel();
        Icard1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Programa de Cambio de Carrera");

        jLabel3.setText("Bienvenido al programa de cambio de carrera, este proyecto fue creado únicamente con el fin de agilizar el  ");

        jLabel4.setText("proceso de cambio de carrera de los alumnos de UVG, siga las Instrucciones para comenzar: ");

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setForeground(new java.awt.Color(51, 153, 0));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Información del alumno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
        );

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setForeground(new java.awt.Color(51, 153, 0));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UVG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel5.setText("Ingrese su nombre:");

        jLabel7.setText("Ingrese su edad:");

        jLabel8.setText("Ingrese su carnet:");

        jLabel9.setText("Ingrese su sexo:");

        Info_Alumno.setBackground(new java.awt.Color(51, 204, 0));
        Info_Alumno.setForeground(new java.awt.Color(255, 255, 255));
        Info_Alumno.setText("Guardar Información");
        Info_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_AlumnoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 255));
        jPanel3.setForeground(new java.awt.Color(51, 153, 0));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese su nueva carrera y la actual:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(854, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
        );

        jLabel11.setText("Carrera Actual:");

        jLabel12.setText("Carrera del cambio:");

        Info_Alumno1.setBackground(new java.awt.Color(51, 0, 255));
        Info_Alumno1.setForeground(new java.awt.Color(255, 255, 255));
        Info_Alumno1.setText("Guardar Información");
        Info_Alumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_Alumno1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setForeground(new java.awt.Color(51, 153, 0));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Información:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13)
        );

        Info2.setColumns(20);
        Info2.setRows(5);
        jScrollPane1.setViewportView(Info2);

        Info1.setColumns(20);
        Info1.setRows(5);
        jScrollPane2.setViewportView(Info1);

        jLabel14.setText("Carrera Actual");

        jLabel15.setText("Carrera Nueva");

        Iname1.setText(".");

        Iage1.setText(".");

        Isex1.setText(".");

        Icard1.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(577, 577, 577))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Iname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Iage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(207, 207, 207)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Icard1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Isex1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Iname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(Iage)
                .addGap(577, 577, 577)
                .addComponent(Isex))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Info_Alumno))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActualCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Info_Alumno1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Info_Alumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(NewCarrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Info_Alumno1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Iname1)
                            .addComponent(Isex1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Iage1)
                            .addComponent(Icard1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Iage)
                            .addComponent(Isex)
                            .addComponent(Iname))
                        .addGap(28, 28, 28)
                        .addComponent(Icard)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Info_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_AlumnoActionPerformed
        // TODO add your handling code here:
        String name1 = name.getText();
        String sex1 = sex.getText();
        String age1 = age.getText();
        float age2 = Float.parseFloat(age1);      
        String card1 = card.getText();
        long card2 = Long.parseLong(card1); 
        NuevoAlumno.setNombre(name1);
	NuevoAlumno.setEdad(age2);
	NuevoAlumno.setSexo(sex1);
	NuevoAlumno.setCarnet(card2); 
        Iname1.setText(String.valueOf("Nombre: "+NuevoAlumno.getNombre()));  
        Iage1.setText(String.valueOf("Edad: "+NuevoAlumno.getEdad())); 
        Isex1.setText(String.valueOf("Sexo: "+NuevoAlumno.getSexo()));
        Icard1.setText(String.valueOf("Carnet: "+NuevoAlumno.getCarnet()));
    }//GEN-LAST:event_Info_AlumnoActionPerformed

    private void Info_Alumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_Alumno1ActionPerformed
        // TODO add your handling code here:
        String ActualCarrier1 = ActualCarrier.getText();
        
        //Ingenieria Mecanica 
        if (ActualCarrier1.equals("Ingenieria en ciencia de la computacion") ||ActualCarrier1.equals("ingenieria en ciencia de la computacion") ){
        NuevoAlumno.llenarCarrera("Ingenieria en ciencia de la computación: ",
        "Ciencias de la Vida","Algoritmos y Programación Básica","Pensamiento Cuantitativo",
        "Comunicación efectiva", "Química General","Introducción a la Ingeniería",
        "coaching para la excelencia",
        
        "Programación Orientada a Objetos", "Estadística 1", "Ciudadanía global", "Física 1",
        "Cálculo1", "Algebra Lineal 1",
        
        "Org. De Computadoras y Assembler", "Física 2", "Cálculo 2", 
        "Programación Plataformas Móviles y Juegos", "Algoritmos y Estructuras de Datos",
        "Guatemala en el contexto mundial",
        
        "Física 3", "Matemática Discreta 1", "Retos Ambientales y sostenibilidad", 
        "Ecuaciones Diferenciales 1", "Investigación y Pensamiento Científico", 
        "Programación de Microprocesadores",
        
        "Bases de Datos", "Ingeniería de Software 1", "Gráficaspor computadora", 
        "Interacción Humano Computador", "Diseño de Videojuegos", "Selectivo de Desarrollo Profesional",
        
        "Emprendimiento e Innovación", "Ingeniería de Software 2", "Sistemas y Tecnologías Web",
        "Selectivo de Desarrollo Profesional", "Lógica Matemática", "Programación Avanzada de Videojuegos",
        
        "Inteligencia Artificial", "Minería de Datos", "Selectivo: Ingeniería Financiera o Microeconomia",
        "Análisis y Diseño de Algoritmos", "Sistemas Operativos", "Desarrollo Ágil de negocios tecnológicos",
        
        "Administración de Proyectos de T", "Data Science 1", "Selectivo", "Redes", "Arquitectura Empresarial", 
        "Modelación y Simulación", 
        
        "Diseño e Innovación en Ingeniería 1", "Computación Paralela y DistribuÍda", "Práctica Profesional",
        "Diseño de Lenguajes de Programación", "Selectivo", "Seguridad en Sistemas de Computación",
        
        "Administración y Mantenimiento sistemas", "Seguridad Ofensiva", "Construcción de Compiladores", 
        "Gestion y admon detalentos", "Planeación Estratégica y Operacional", "Diseño e Innovación en Ingeniería 2");
        Info2.setText(String.valueOf(NuevoAlumno.getCarrera()));}
        
        if ((ActualCarrier1.equals("ingenieria mecanica")) ||(ActualCarrier1.equals("Ingenieria mecanica"))){
        NuevoAlumno.llenarNuevaCarrera("ingeniería mecánica: ",
        "Pensamiento cuantitativo", "introducción a la ingeniería mecánica","dibujo mecánico",
        "algoritmos y programación básica", "Química general","ciudadanía global",
        "coachingpara la excelencia",
        
        "cálculo1", "física 1", "manufactura digital", "ciencias dela vida", "estadística 1", 
        "comunicación efectiva",
        
        "Cálculo 2", "Álgebra Lineal 1", "Física 2", "Materiales 1",
        "Soldadura industrial", "Investigación y pensamiento científico",
        
        "guatemala en el contexto mundial", "ecuaciones diferenciales 1", 
        "mecanica 1: estatica", "introduccion a ingenieria electrica", 
        "maquinas herramienta", "retos ambientes y sostenibilidad",
        
        "metodos numéricos en ingenieria mecanica", "termodinamica 1", 
        "mecanica 2: dinamica", "resistencia de materiales 1", "selectivo (formacion general)", 
        "emprendimiento e innovacion", "mecanica de fluidos 1", "termodinamica 2", 
        "resistencia de materiales 2", "materiales 2", "mecanismos", "selectivo (formacion general)",
        
        "mecanica de fluidos 2", "diseño de ingenieria mecanica 1", "transferencia de calor", 
        "introduccion a diseño y manufactura cad cam", "procesos industriales", 
        "economia de empresas",
        
        "máquinas electromecanicas", "vibraciones mecanicas", "motores de combustion interna", 
        "diseño de ingenieria mecanica 2", "sistemas hidraulicos y neumaticos", 
        "curso selectivo (area de ingenieria para el desarrollo)",
        
        "generacion de potencia", "ingenieria economica", "energia renovable (ingenieria mecanica)", 
        "refrigeracion y acondicionamiento de aire", "diseño e innovacion en ingenieria 1", 
        "elementos finitos",
        
        "sistemas de control", "gestion de mantenimiento industrial", "curso selectivo (área profesional)",
        "gestion de proyectos", "diseño e innovacion en ingeniería 2", "practica profesional");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
        
         if (ActualCarrier1.equals("Matematica") ||ActualCarrier1.equals("matematica")){
        NuevoAlumno.llenarNuevaCarrera( "Matematica: ", 
        "pensamiento cuantitativo", "ciencias de la vida", "coaching para la excelencia", 
        "comunicacion efectiva", "algoritmos y programacion basica", "geometria elemental", 
        "quimica general",
        
        "ciudadania global", "estadistica 1", "geometria moderna", "fisica 1", "calculo 1", 
        "programacion orientada a objetos",
        
        "guatemala en el contexto mundial", "algebra lineal 1", "fisica 2", "matematica discreta 1", 
        "calculo 2", "herramientas tecnologicas para matematica",
        
        "retos ambientales y sostenibilidad", "investgacion y pensamiento cientifico", 
        "ecuaciones diferenciales 1", "teoria de conjuntos", "calculo 3", "algebra lineal 2",
        
        "analisis de variabale real 1", "algebra moderna 1", "ecuaciones diferenciales 2",  
        "estadisticas matematica", "estadistica 2", "curso selectivo de desarrollo profesional",
        "emprendimiento e innovacion", "analisis de variable real 2", "algebra moderna 2", 
        "fisica 3", "data mining", "curso selectivo de desarrollo profesional", 
        
        "metodos numericos 1", "algoritmos y estructuras de datos", "seminario 1 de matematica aplicada", 
        "teoria de la medida", "topologia", "investigacion de operaciones",
        
        "modelacion y simulacion", "data science 1", "seminario 2 de matematica aplicada", 
        "teoria de probabilidades", "metodos numericos 2", "administracion financiera"," ",
        
        "geometria diferencial", "analisis de variable compleja", "seminario 3 de matematica aplicada", 
        "analisis funcional", "practica profesional", "trabajo de graduacion", "curso selectivo educacion",
        " ", " ", " ", " ");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
        
         if (ActualCarrier1.equals("Administracion") ||ActualCarrier1.equals("administracion")){
        NuevoAlumno.llenarNuevaCarrera( "Administracion: ",
        "pensamiento cuantitativo", "algoritmos y programacion basica", "ciencias de la vida", 
        "contabilidad 1", "ciudadania global", "introduccion a la innovacion y los negocios", "ingles",
        "calculo 1", "fisica 1", "estadistica 1", "quimica general", "comunicacion efectiva", 
        "contabilidad 2",
        
        "calculo 2", "fisica 2", "estadistica 2", "guatemala en el contexto mundial", "microeconomia",
        "ecuaciones diferenciales 1", "retos ambientales y sostenibilidad2", 
        "anthropology", "culture and bussiness", "investigacion y pensamiento cientifico 2",
        "macroeconomia", "contabilidad de costos",
       
        "metodos numericos 1", "ingenieria economica", "curso selectivo", "design thinking", 
        "mercadotecnia 1", "investigacion de operaciones", 
        
        "emprendimiento e innovacion", "data mining", "administracion de empresas familiares", 
        "formulacion y evaluacion de proyectos", "practica profesional", "curso selectivo", 
        "administracion financiera", 
        
        "entorno legal de negocios", "gestion de proyectos", "diseño e innovacion en ingenieria 1", 
        "valuacion de activos", "administracion de la cadena de suministro", "comercio internacional", 
        "teoria de inversiones",
        
        "desarrollo agil de negocios", "tecnologicos", "gestion y administracion de talentos", 
        "diseño e innovacion en ingenieria 2", "finanzas corporativas internacionales", 
        "administracion global y geopolitica",  "", "", "", "", "", "", "", "", "", "");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}

         if (ActualCarrier1.equals("Ingeneria Industrial") ||ActualCarrier1.equals("ingeneria industrial")){
        NuevoAlumno.llenarNuevaCarrera( "Ingeneria Industrial: ",
        "dibujo cad", "pensamiento cuantitativo", "ciencias de la vida", "comunicacion efectiva",  
        "quimica general", "introduccion a la ingenieria civil", "coaching para la excelencia", "ingles",
        "estadistica 1", "algoritmos y programacion basica", "ciudadania global", "fisica 1", "calculo 1", 
        "materiales 1",
        "guatemala en el contexto mundial", "fisica 2", "geologia", "calculo 2", "algebra lineal 1", 
        "modelado de informacion para edificaciones",
        "retos ambientales y sostenibilidad", "selectivo microeconomia o investigacion de operaciones", 
        "mecanica 1 (estatica)", "carpinteria", "ecuaciones diferenciales", "resistencia de materiales 1", 
        "topografia general","mecanica de fluidos 1", "analisis estructural 1", "mecanica de suelos", 
        "curso selectivo (formacion general)", 
        "resistencia de materiales 2", "sig y geodesia", "analisis estructural 2", "cimentaciones", 
        "curso selectivo (formacion general)", "emprendimiento e innovavion", "hidraulica general", 
        "gestion de proyectos", "estructuras de madera", "concreto 1", "estructuras de acero 1", 
        "dispositivos electricos",
        "concreto 2", "estructuras de acero 2", "hidrologia", "ingenieria sanitaria", 
        "dispositivos electromecanicos", "curso selectivo",
        "introduccion a la ingenieria sismo resistente", "diseño de carreteras", "ingenieria economica", 
        "administracion", "energia renovable (ingenieria mecanica)", "diseño e innovacion 1",
        "diseño de obras hidraulicas", "diseño estructural", "diseño de infraestructura vial", 
        "elementos finitos", "eficiencia energetica en edificaciones", "diseño e innovacion 2");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));} 
         
         
         
         
         
         
        
       //Ciencias de las computación         
        String NewCarrier1 = NewCarrier.getText();
        if (NewCarrier1.equals("ingenieria mecanica") ||NewCarrier1.equals("Ingenieria mecanica") ){
        NuevoAlumno.llenarNuevaCarrera("ingeniería mecánica: ",
        "Pensamiento cuantitativo", "introducción a la ingeniería mecánica","dibujo mecánico",
        "algoritmos y programación básica", "Química general","ciudadanía global",
        "coachingpara la excelencia",
        
        "cálculo1", "física 1", "manufactura digital", "ciencias dela vida", "estadística 1", 
        "comunicación efectiva",
        
        "Cálculo 2", "Álgebra Lineal 1", "Física 2", "Materiales 1",
        "Soldadura industrial", "Investigación y pensamiento científico",
        
        "guatemala en el contexto mundial", "ecuaciones diferenciales 1", 
        "mecanica 1: estatica", "introduccion a ingenieria electrica", 
        "maquinas herramienta", "retos ambientes y sostenibilidad",
        
        "metodos numéricos en ingenieria mecanica", "termodinamica 1", 
        "mecanica 2: dinamica", "resistencia de materiales 1", "selectivo (formacion general)", 
        "emprendimiento e innovacion", "mecanica de fluidos 1", "termodinamica 2", 
        "resistencia de materiales 2", "materiales 2", "mecanismos", "selectivo (formacion general)",
        
        "mecanica de fluidos 2", "diseño de ingenieria mecanica 1", "transferencia de calor", 
        "introduccion a diseño y manufactura cad cam", "procesos industriales", 
        "economia de empresas",
        
        "máquinas electromecanicas", "vibraciones mecanicas", "motores de combustion interna", 
        "diseño de ingenieria mecanica 2", "sistemas hidraulicos y neumaticos", 
        "curso selectivo (area de ingenieria para el desarrollo)",
        
        "generacion de potencia", "ingenieria economica", "energia renovable (ingenieria mecanica)", 
        "refrigeracion y acondicionamiento de aire", "diseño e innovacion en ingenieria 1", 
        "elementos finitos",
        
        "sistemas de control", "gestion de mantenimiento industrial", "curso selectivo (área profesional)",
        "gestion de proyectos", "diseño e innovacion en ingeniería 2", "practica profesional");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
        
        if (NewCarrier1.equals("Ingenieria en ciencia de la computacion") || NewCarrier1.equals("ingenieria en ciencia de la computacion") ){
        NuevoAlumno.llenarCarrera("Ingenieria en ciencia de la computación: ",
        "Ciencias de la Vida","Algoritmos y Programación Básica","Pensamiento Cuantitativo",
        "Comunicación efectiva", "Química General","Introducción a la Ingeniería",
        "coaching para la excelencia",
        
        "Programación Orientada a Objetos", "Estadística 1", "Ciudadanía global", "Física 1",
        "Cálculo1", "Algebra Lineal 1",
        
        "Org. De Computadoras y Assembler", "Física 2", "Cálculo 2", 
        "Programación Plataformas Móviles y Juegos", "Algoritmos y Estructuras de Datos",
        "Guatemala en el contexto mundial",
        
        "Física 3", "Matemática Discreta 1", "Retos Ambientales y sostenibilidad", 
        "Ecuaciones Diferenciales 1", "Investigación y Pensamiento Científico", 
        "Programación de Microprocesadores",
        
        "Bases de Datos", "Ingeniería de Software 1", "Gráficaspor computadora", 
        "Interacción Humano Computador", "Diseño de Videojuegos", "Selectivo de Desarrollo Profesional",
        
        "Emprendimiento e Innovación", "Ingeniería de Software 2", "Sistemas y Tecnologías Web",
        "Selectivo de Desarrollo Profesional", "Lógica Matemática", "Programación Avanzada de Videojuegos",
        
        "Inteligencia Artificial", "Minería de Datos", "Selectivo: Ingeniería Financiera o Microeconomia",
        "Análisis y Diseño de Algoritmos", "Sistemas Operativos", "Desarrollo Ágil de negocios tecnológicos",
        
        "Administración de Proyectos de T", "Data Science 1", "Selectivo", "Redes", "Arquitectura Empresarial", 
        "Modelación y Simulación", 
        
        "Diseño e Innovación en Ingeniería 1", "Computación Paralela y DistribuÍda", "Práctica Profesional",
        "Diseño de Lenguajes de Programación", "Selectivo", "Seguridad en Sistemas de Computación",
        
        "Administración y Mantenimiento sistemas", "Seguridad Ofensiva", "Construcción de Compiladores", 
        "Gestion y admon detalentos", "Planeación Estratégica y Operacional", "Diseño e Innovación en Ingeniería 2");
        Info2.setText(String.valueOf(NuevoAlumno.getCarrera()));}
               
         if (NewCarrier1.equals("Matematica") ||NewCarrier1.equals("matematica")){
        NuevoAlumno.llenarNuevaCarrera( "Matematica: ", 
        "pensamiento cuantitativo", "ciencias de la vida", "coaching para la excelencia", 
        "comunicacion efectiva", "algoritmos y programacion basica", "geometria elemental", 
        "quimica general",
        
        "ciudadania global", "estadistica 1", "geometria moderna", "fisica 1", "calculo 1", 
        "programacion orientada a objetos",
        
        "guatemala en el contexto mundial", "algebra lineal 1", "fisica 2", "matematica discreta 1", 
        "calculo 2", "herramientas tecnologicas para matematica",
        
        "retos ambientales y sostenibilidad", "investgacion y pensamiento cientifico", 
        "ecuaciones diferenciales 1", "teoria de conjuntos", "calculo 3", "algebra lineal 2",
        
        "analisis de variabale real 1", "algebra moderna 1", "ecuaciones diferenciales 2",  
        "estadisticas matematica", "estadistica 2", "curso selectivo de desarrollo profesional",
        "emprendimiento e innovacion", "analisis de variable real 2", "algebra moderna 2", 
        "fisica 3", "data mining", "curso selectivo de desarrollo profesional", 
        
        "metodos numericos 1", "algoritmos y estructuras de datos", "seminario 1 de matematica aplicada", 
        "teoria de la medida", "topologia", "investigacion de operaciones",
        
        "modelacion y simulacion", "data science 1", "seminario 2 de matematica aplicada", 
        "teoria de probabilidades", "metodos numericos 2", "administracion financiera"," ",
        
        "geometria diferencial", "analisis de variable compleja", "seminario 3 de matematica aplicada", 
        "analisis funcional", "practica profesional", "trabajo de graduacion", "curso selectivo educacion",
        " ", " ", " ", " ");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
         
        if (NewCarrier1.equals("Administracion") ||NewCarrier1.equals("administracion")){
        NuevoAlumno.llenarNuevaCarrera( "Matematica: ",
        "pensamiento cuantitativo", "algoritmos y programacion basica", "ciencias de la vida", 
        "contabilidad 1", "ciudadania global", "introduccion a la innovacion y los negocios", "ingles",
        "calculo 1", "fisica 1", "estadistica 1", "quimica general", "comunicacion efectiva", 
        "contabilidad 2",
        
        "calculo 2", "fisica 2", "estadistica 2", "guatemala en el contexto mundial", "microeconomia",
        "ecuaciones diferenciales 1", "retos ambientales y sostenibilidad2", 
        "anthropology", "culture and bussiness", "investigacion y pensamiento cientifico 2",
        "macroeconomia", "contabilidad de costos",
       
        "metodos numericos 1", "ingenieria economica", "curso selectivo", "design thinking", 
        "mercadotecnia 1", "investigacion de operaciones", 
        
        "emprendimiento e innovacion", "data mining", "administracion de empresas familiares", 
        "formulacion y evaluacion de proyectos", "practica profesional", "curso selectivo", 
        "administracion financiera", 
        
        "entorno legal de negocios", "gestion de proyectos", "diseño e innovacion en ingenieria 1", 
        "valuacion de activos", "administracion de la cadena de suministro", "comercio internacional", 
        "teoria de inversiones",
        
        "desarrollo agil de negocios", "tecnologicos", "gestion y administracion de talentos", 
        "diseño e innovacion en ingenieria 2", "finanzas corporativas internacionales", 
        "administracion global y geopolitica",  "", "", "", "", "", "", "", "", "", "");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
        
        if (NewCarrier1.equals("Ingeneria Industrial") ||NewCarrier1.equals("ingeneria industrial")){
        NuevoAlumno.llenarNuevaCarrera( "Ingeneria Industrial: ",
        "dibujo cad", "pensamiento cuantitativo", "ciencias de la vida", "comunicacion efectiva",  
        "quimica general", "introduccion a la ingenieria civil", "coaching para la excelencia", "ingles",
        "estadistica 1", "algoritmos y programacion basica", "ciudadania global", "fisica 1", "calculo 1", 
        "materiales 1",
        "guatemala en el contexto mundial", "fisica 2", "geologia", "calculo 2", "algebra lineal 1", 
        "modelado de informacion para edificaciones",
        "retos ambientales y sostenibilidad", "selectivo microeconomia o investigacion de operaciones", 
        "mecanica 1 (estatica)", "carpinteria", "ecuaciones diferenciales", "resistencia de materiales 1", 
        "topografia general","mecanica de fluidos 1", "analisis estructural 1", "mecanica de suelos", 
        "curso selectivo (formacion general)", 
        "resistencia de materiales 2", "sig y geodesia", "analisis estructural 2", "cimentaciones", 
        "curso selectivo (formacion general)", "emprendimiento e innovavion", "hidraulica general", 
        "gestion de proyectos", "estructuras de madera", "concreto 1", "estructuras de acero 1", 
        "dispositivos electricos",
        "concreto 2", "estructuras de acero 2", "hidrologia", "ingenieria sanitaria", 
        "dispositivos electromecanicos", "curso selectivo",
        "introduccion a la ingenieria sismo resistente", "diseño de carreteras", "ingenieria economica", 
        "administracion", "energia renovable (ingenieria mecanica)", "diseño e innovacion 1",
        "diseño de obras hidraulicas", "diseño estructural", "diseño de infraestructura vial", 
        "elementos finitos", "eficiencia energetica en edificaciones", "diseño e innovacion 2");
        Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));} 
	
	if ((ActualCarrier1.equals("Ingenieria en Alimentos"))){
        NuevoAlumno.llenarNuevaCarrera("Ingenieria en Alimentos:",
	"pensamiento cuantitativo", "ciudadania global", "ciencias de la vida", "algoritmos y programacion basica", "introduccion a la ingenieria de alimentos", "quimica 1",
	//se ignora coaching
	"comunicacion efectiva", "estadistica 1", "qumica 2", "fisica 1", "calculo 1", "procesamiento de planificacion y confiteria",			
	"investigacion y pensamiento cientifico", "quimica organica 1", "calculo 2", "fisica 2", "quimica analitica", "dibujo cad",
	"guatemala en el contexto mundial", "retos ambientales y sostenibilidad", "quimica organica 2", "algebra lineal 1", "fisicoquimica 1", "analisis quimico en la industria de alimentos",
	"procesamiento de productos hortofructicolas, lacteos y carnes", "ecuaciones diferenciales 1", "balance de masa y energia", "quimica de alimentos", "bioquimica y nutricion aplicada", "microbiologia de alimentos 1",
	"selectivo de desarrollo profesional", "analisis sensorial de alimentos", "bioquimica de alimentos", "toxicologia y microbiologia aplicada", "flujo de fluidos", "estadistica 2",
	"termodinamica quimica 1", "transferencia de calor", "manejo de solidos", "tecnologia en la industria de alimentos", "control de calidad e inocuidad de alimentos", "selectivo de desarollo profesional",
	"transferencia de masa 1", "tecnologia de empaques para la industria de alimentos", "sistemas de gestion en la industria de alimentos", "legislacion alimentaria", "emprendimiento e innovacion", "", //aqui hay solo 5 clases			       
        "ingenieria y procesos en la industria de alimentos 1", "investigacion y desarollo de nuevos productos", "biotecnologia aplicada a la industria alimentaria", "diseño de plantas de alimentos", "investigacion de operaciones", "diseño e innovacion en ingenieria 1",
	"formulacion y evaluacion de proyectos de inversion", "administracion de la cadena de suministros", "innovacion y formulaciones en la industria de alimentos", "ingenieria y procesos en la industria de alimentos 2", "mercadeo aplicado a productos alimenticios", "diseño e innovacion en ingenieria de alimentos 2");
	Info1.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));} 
	    
    }//GEN-LAST:event_Info_Alumno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActualCarrier;
    private javax.swing.JLabel Iage;
    private javax.swing.JLabel Iage1;
    private javax.swing.JLabel Icard;
    private javax.swing.JLabel Icard1;
    private javax.swing.JLabel Iname;
    private javax.swing.JLabel Iname1;
    private javax.swing.JTextArea Info1;
    private javax.swing.JTextArea Info2;
    private javax.swing.JButton Info_Alumno;
    private javax.swing.JButton Info_Alumno1;
    private javax.swing.JLabel Isex;
    private javax.swing.JLabel Isex1;
    private javax.swing.JTextField NewCarrier;
    private javax.swing.JTextField age;
    private javax.swing.JTextField card;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sex;
    // End of variables declaration//GEN-END:variables
}
